### ISSUE TITLE
RosAria ArRobot::myPacketReader: Timed out

### ISSUE THREAD

**Issue by nrkumar93** [amor-ros-pkg/rosaria#31]
i am working with Pioneer 3DX and using RosAria library to control the robot. The rosaria library was working fine. But suddenly today I encountered this problem and I am not able to solve. On running rosaria rode using 'rosrun rosaria RosAria' I face the following serial error. I have set full permissions for my serial port.

ramkumar@ramkumar-Inspiron-7720:~$ rosrun rosaria RosAria rosrun rosaria RosAria _port:=/dev/ttyUSB0
[ INFO] [1422207128.792943336]: RosAria: using port: [/dev/ttyUSB0]
Could not connect to simulator, connecting to robot through serial port /dev/ttyUSB0.
Syncing 0
Syncing 1
Syncing 2
Connected to robot.
Name: IIT-madras_3906
Type: Pioneer
Subtype: p3dx-sh
ArConfig: Config version: 2.0
Loaded robot parameters from p3dx-sh.p
ArRobotPacketReceiver::receivePacket: bad packet, bad checksum
ArRobotConnector: Connecting to MTX batteries (if neccesary)...
ArRobotConnector: Connecting to MTX sonar (if neccesary)...
[ INFO] [1422207129.572967595]: Setting TicksMM from ROS Parameter: 128
[ INFO] [1422207129.575718946]: Setting DriftFactor from ROS Parameter: 0
[ INFO] [1422207129.577907662]: Setting RevCount from ROS Parameter: 16570
ArRobot::myPacketReader: Timed out (4) at 1002 (200 into cycle after sleeping 200)
[ INFO] [1422207129.817593371]: RosAria: publishing new recharge state 0.
[ INFO] [1422207129.817769667]: RosAria: publishing new motors state 0.
ArRobot::myPacketReader: Timed out (4) at 1203 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 1404 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 1604 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 1804 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 2004 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 2205 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 2405 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 2605 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 2805 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 3006 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 3206 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 3406 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 3606 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 3807 (201 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 4007 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 4207 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 4407 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 4607 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 4808 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 5008 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 5208 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 5408 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 5609 (201 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 5809 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 6009 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 6209 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 6409 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 6610 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 6810 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 7010 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 7210 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 7411 (201 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 7611 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 7811 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 8011 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 8212 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 8412 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 8612 (200 into cycle after sleeping 200)
ArRobot::myPacketReader: Timed out (4) at 8812 (200 into cycle after sleeping 200)
Losing connection because no odometry received from robot in 8058 milliseconds (greater than the timeout of 8000).
ArSerialConnection::read:  Connection invalid.

Please help

**Comment by dawonn** [comment]
Are you sure the serial cable is fully connected? It looks like it's opening the port fine but something is preventing ARIA from communicating with the robot.

If so, it appears the ros-aria wrapper is working ok, but the problem is Aria specific. if problems persist try asking on the aria mailing list. The audience is larger and the aria developers monitor it rather closely: http://robots.mobilerobots.com/wiki/Aria-users_Mailing_List

**Comment by nrkumar93** [comment]
I got this problem fixed. I had mounted my robot over a deck for testing purpose and that was causing the problem. Pioneer is designed to make an initial jerk that works as a feedback mechanism (syncing 0 1 2). B4 8058ms u need to make a small jerk rotating a wheel manually, it solves the problem.
