### ISSUE TITLE
No such file Aria.h

### ISSUE THREAD

**Issue by End-Effector** [amor-ros-pkg/rosaria#42]
I can not install this package.

I'm getting this error:

Scanning dependencies of target RosAria
[ 98%] Building CXX object rosaria/CMakeFiles/RosAria.dir/RosAria.cpp.o
/home/paulo/catkin_ws/src/rosaria/RosAria.cpp:6:25: fatal error: Aria/Aria.h: No such file or directory
   #include <Aria/Aria.h>

Solutions?Thx so much.

**Comment by End-Effector** [comment]
It's working now. I forgot to install Aria before the catkin_make.

**Comment by NCHUPJ** [comment]
How to install Aria?
I can't get in from http://robots.mobilerobots.com/wiki/Aria.

**Comment by reed-adept** [comment]
Mobilerobots took down the old websites.   Other people here may have
copies of ARIA releases.   And I also made a fork called AriaCoda at
http://github.com/reedhedges/AriaCoda that should also work though you
may need to rename the directory to Aria, or tell rosaria to use the
specific path to AriaCoda.    At some point in the future we could
automate rosaria's use of either its own copy of Aria or of AriaCoda
(either by cloning it from github or via a .deb package) but waiting
to see if there is enough interest/demand for that.

Reed
