### ISSUE TITLE
rosaria fails to connect with 'box' in MobileSim

### ISSUE THREAD

**Issue by shionlau** [amor-ros-pkg/rosaria#47]
The 'box' model is defined here
http://robots.mobilerobots.com/MobileSim/download/current/README.html#modeldefs

> MobileSim includes some "box" model definitions in its model definitions file PioneerRobotModels.world.inc. These are 0.5 x 0.5 meter objects that you can place anywhere in the map, and move with the mouse during the simulation. These boxes are created in the same way as robots, using the -r command line argument. 

I added a 'box' model in a MobileSim map and got the following error when running rosaria:

> Syncing 0
> Syncing 1
> Syncing 2
> Connected to robot.
> Name: MobileSim
> Type: Pioneer
> Subtype: box
> Error: Have no parameters for this robot, bad configuration or out of date Aria
> Failed to connect to robot.
> [ERROR] [1450913329.046775885]: RosAria: ARIA could not connect to robot! (Check ~port parameter is correct, and permissions on port device.)
> [FATAL] [1450913329.046861452]: RosAria: ROS node setup failed... 

rosaria works well if I add a 'real' robot model, e.g. p3dx, but fails to work with the 'box'. Does anyone know what the problem is?

**Comment by reed-adept** [comment]
Boxes in MobileSim are not intended to be controlled remotely, the fact that you can connect to them is sort of an accidental side effect. Maybe could be called a bug.     The problem is that ARIA does not recognize the type of the robot. You would need to create an ARIA parameter file for "box" (params/box.p).
