### ISSUE TITLE
compile error: no matching function NodeHandle::param() in ros hydro

### ISSUE THREAD

**Issue by lvxingzhe1991** [amor-ros-pkg/rosaria#54]
/home/dxxy/mcatkin_ws/src/rosaria/RosAria.cpp: In member function ‘int RosAriaNode::Setup()’:
/home/dxxy/mcatkin_ws/src/rosaria/RosAria.cpp:517:63: error: no matching function for call to ‘ros::NodeHandle::param(const char [16], double)’
   double cmdvel_timeout_param = n.param("cmd_vel_timeout", 0.6);
                                                               ^
In file included from /opt/ros/hydro/include/ros/ros.h:45:0,
                 from /home/dxxy/mcatkin_ws/src/rosaria/RosAria.cpp:8:
/opt/ros/hydro/include/ros/node_handle.h:1912:8: note: candidate: template<class T> void ros::NodeHandle::param(const string&, T&, const T&) const

**Comment by reed-adept** [comment]
Perhaps this function was added after the Hydro release? Does anyone know?

**Comment by lvxingzhe1991** [comment]
I do not know

**Comment by ongun-kanat** [comment]
2 parameter version is added in indigo. Hydro only has 3 parameter version of ros::param as in the API docs:
http://docs.ros.org/hydro/api/roscpp/html/namespaceros_1_1param.html#a72d230225ecb3fd770946afd0e1e6af4

http://docs.ros.org/indigo/api/roscpp/html/namespaceros_1_1param.html#a72d230225ecb3fd770946afd0e1e6af4

**Comment by reed-adept** [comment]
I changed to use the other form of param(), can you test in Hydro?  Thanks

**Comment by reed-adept** [comment]
I am presuming this is now fixed after commit aa8d5f7, but we are no longer testing RosAria on hydro.   If someone is using hydro, and is able to test, and it is still a problem, please comment/reopen this issue report. Thanks.
