### ISSUE TITLE
Website for downloading Aria is down

### ISSUE THREAD

**Issue by UditSinghParihar** [amor-ros-pkg/rosaria#61]
Sir, I am following [How to use ROSARIA](http://wiki.ros.org/ROSARIA/Tutorials/How%20to%20use%20ROSARIA) tutorial. But at step [0.1](http://wiki.ros.org/ROSARIA/Tutorials/How%20to%20use%20ROSARIA#Install_ARIA_and_Build_ROSARIA) the link [given](http://robots.mobilerobots.com/wiki/Aria) for downloading latest version of Aria is down.
Could you provide an alternate link to download 64-bit ARIA package (amd64) or suggest another library to control p3dx bot.

Thanks

**Comment by reedhedges** [comment]
ARIA is no longer maintained by Omron/Adept.  I made a fork at http://github.com/reedhedges/AriaCoda but it is source code repository only, no debian packages, and not yet intergrated into rosaria in any way.   If you can find any copy of ARIA (my fork or previous official version) you can just install it on your system, and re-run the catkin build process (perhaps with `--fork-cmake`) and it should detect it installed on the system.  If someone wants to either connect the rosaria build system to cloning my fork and building it, or just including a copy of ARIA inside ROSARIA, it may be useful to other people.   Discuss here or on the ros-sig-pioneer ROS email list.

**Comment by UditSinghParihar** [comment]
Thanks for the reply but somehow I previously downloaded the debian package for aria for 64bit ubuntu. I have uploaded the debian file for anyone to download [here](https://drive.google.com/file/d/1osU0jeldyJ8uS3KIlJlkm1k4EwwG3RPy/view?usp=sharing) .

**Comment by reedhedges** [comment]
It looks like the old MobileRobots.com websites are probably permanently down now.
You can access the support website/knowledge base/wiki at archive.org:

<https://web.archive.org/web/20180214114520/http://robots.mobilerobots.com/wiki/Main_Page>
