### ISSUE TITLE
Change TicksMM, RevCount, DriftFactor has no Effect

### ISSUE THREAD

**Issue by svhoy** [amor-ros-pkg/rosaria#68]
Hello, 

we are starting our Pioneer 3 AT with RosAria with the following Config: 
```
<node name="RosAria" pkg="rosaria" type="RosAria" ns= "robot2">
  <param name="port" value="/dev/ttyUSB1" type="string"/>
  <param name ="debug_aria" value="false" />
  <param name ="TicksMM" value="128" />
  <param name ="RevCount" value="16500" />
  <param name ="DriftFactor" value="0" />
  <param name ="odom_frame" value="robot2/odom"/>
  <param name ="base_link_frame" value="robot2/base_link"/>
  <param name ="bumpers_frame" value="robot2/bumpers"/>
  <param name ="sonar_frame" value="robot2/sonar"/>
 </node>
```

So after that we can see in the topic /robot2/RosAria/parameters_update that the parameters a changed from the default ones. When we are drive 5 metres our robot now, there is a drift about 30cm to the left. So we are changed the DriftFactor to drifferent parameters. But there are no driffience in the drift from the robot when we are driving with it, so no matter how we change the driftFactor there are always 30cm drift to the left. 

System Info: 

- Raspberry Pi 4 
- Ubuntu Mate 20.04
- ROS Noetic

Did we something work or might be there a bug. 

Thanks for your help!

**Comment by reedhedges** [comment]
Can you paste the log output from the rosaria node and Aria.log ?

There are a few ways to set calibration parameters, you can always change
them in the robot firmware.  When you change the parameters from ros, it
should send commands to the robot which set them temporarily (for this
session).

So first we should verify that rosaria is receiving the update, and is then
sending the commands, or isn't for some reason.    If you want to increase
amount of logging, you can set the debug_aria parameter to true and a large
amount of data including all data sent to and from the robot will be logged
to Aria.log file.

Also, did you build rosaria using Aria 2.x from Adept/MobileRobots, or
using AriaCoda?

**Comment by svhoy** [comment]
Hi, 

thanks for your reply. We worked with Aria 2.x before and now changed to AriaCoda thanks to your question. Now it seems to work fine. So I think there are an issue when your are working with Aria 2.x and the solution is to change to AriaCoda.
